academy/urls.py
from academy import views

from django.urls import path

app_name = "academy"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("student/", views.StudentListView.as_view(), name="students_list"),
    path("student/<int:pk>", views.StudentDetailView.as_view(), name="student_detail"),
    path("student/<int:pk>/studentprofile/", views.StudentProfileDetailView.as_view(), name="students_profile"),
    path("student/create/", views.StudentCreateView.as_view(), name="student_creation"),
    path("student/<int:pk>/update/", views.StudentUpdateView.as_view(), name="student_updating"),
    path("student/<int:pk>/delete/", views.StudentDeleteView.as_view(), name="student_delete"),
    # path("studentprofile/<int:pk>", views.StudentProfileDetailView.as_view(), name="students_profile"),
    path("subject/", views.SubjectListView.as_view(), name="subject_list"),
    path("subject/<int:pk>", views.SubjectDetailView.as_view(), name="subject_detail"),
    path("teacher/", views.TeacherListView.as_view(), name="teacher_list"),
    path("teacher/<int:pk>", views.TeacherDetailView.as_view(), name="teacher_detail"),
    path("contact-us/", views.contact_us, name="contact-us"),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("academy.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

academy/models.py
from django.db import models
from django.urls import reverse
from phone_field import PhoneField


class Teacher(models.Model):
    teacher_first_name = models.CharField(max_length=30)
    teacher_last_name = models.CharField(max_length=30)
    seniority = models.IntegerField()

    def __str__(self):
        return self.teacher_first_name


class TeacherProfile(models.Model):
    teacher = models.OneToOneField(Teacher, on_delete=models.CASCADE)
    hobby = models.CharField(max_length=200, default=None)

    def __str__(self):
        return f"Student: {self.teacher} Profile. Student's hobby is {self.hobby}"


class Student(models.Model):
    student_first_name = models.CharField(max_length=30)
    student_last_name = models.CharField(max_length=30)
    course = models.IntegerField()
    teacher = models.ManyToManyField(Teacher)

    def __str__(self):
        return self.student_first_name

    def get_absolute_url(self):
        return reverse("academy:student_detail", args=[str(self.id)])


class StudentProfile(models.Model):
    some_student = models.OneToOneField(Student, on_delete=models.CASCADE)
    hobby = models.CharField(max_length=200, default=None)
    religion = models.CharField(max_length=30)
    age = models.IntegerField(default=None)
    birth_date = models.DateField()

    def __str__(self):
        return f"Student: {self.some_student} Profile. Student's hobby is {self.hobby}"


class Subjects(models.Model):
    teacher_name = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    student_name = models.ManyToManyField(Student)
    subject_name = models.CharField(max_length=25)
    lecture_amount = models.IntegerField()
    lecture_duration = models.IntegerField()

    def __str__(self):
        return self.subject_name

    def get_absolute_url(self):
        return reverse("academy:subject_detail", args=[str(self.id)])

celery_beat/models.py
from django.db import models


class Author(models.Model):
    author = models.CharField(max_length=35)
    birth_date = models.CharField(max_length=70)
    hometown = models.CharField(max_length=30)
    description = models.CharField(max_length=500)


class Quote(models.Model):
    quote = models.CharField(max_length=300)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.author

academy/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone


class ReminderForm(forms.Form):
    from_email = forms.EmailField(required=True)
    message = forms.CharField(required=True)
    datetime = forms.DateTimeField(required=True)

    def clean_datetime(self):
        data = self.cleaned_data["datetime"]
        now = timezone.now()

        if data < now:
            raise ValidationError("Incorrect! Datetime can't be in the past!")

        if data > now + datetime.timedelta(days=2):
            raise ValidationError("Incorrect! The specified datetime is out of allowed range (2 days)!")
        return data

academy/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Count, Avg, Min
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator

from django.views import generic
from django.views.decorators.cache import cache_page

from academy.models import Student, StudentProfile, Subjects, Teacher
from .forms import ReminderForm
from .tasks import send_email


class IndexView(generic.ListView):
    template_name = "academy/index.html"
    queryset = Student.objects.all()


@method_decorator(cache_page(20), "get")
class StudentListView(generic.ListView):
    model = Student
    template_name = "academy/students_list.html"
    paginate_by = 999
    # queryset = Student.objects.prefetch_related("teacher")
    queryset = Student.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["avg_count"] = Student.objects.aggregate(Avg("course")).get("course__avg")
        return context


class StudentDetailView(generic.DetailView):
    model = Student
    template_name = "academy/student_detail.html"


class StudentCreateView(LoginRequiredMixin, generic.CreateView):
    model = Student
    fields = ["student_first_name", "student_last_name", "course"]


class StudentUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Student
    fields = ["student_first_name", "student_last_name", "course"]


class StudentDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Student
    success_url = reverse_lazy("academy:students_list")


class StudentProfileDetailView(generic.DetailView):
    model = StudentProfile
    template_name = "academy/student_profile.html"


class SubjectListView(generic.ListView):
    model = StudentProfile
    template_name = "academy/subject_list.html"
    paginate_by = 10
    queryset = Subjects.objects.select_related("teacher_name").annotate(student_count=Count("student_name__id"))


class SubjectDetailView(generic.DetailView):
    model = Subjects
    template_name = "academy/subject_detail.html"
    queryset = Subjects.objects.annotate(student_count=Count("student_name__id"))


@method_decorator(cache_page(15), "get")
class TeacherListView(generic.ListView):
    model = Teacher
    template_name = "academy/teacher_list.html"
    paginate_by = 800
    # queryset = Teacher.objects.prefetch_related("subjects_set").all()
    queryset = Teacher.objects.all()

    # @method_decorator(cache_page(15))
    # def get(self, request, *args, **kwargs):
    #     return super(TeacherListView, self).get(request, args, kwargs)


class TeacherDetailView(generic.DetailView):
    model = Teacher
    template_name = "academy/teacher_detail.html"


# @cache_page(15)
def contact_us(request):
    if request.POST:
        form = ReminderForm(request.POST)
        if form.is_valid():
            send_email.apply_async(
                kwargs={
                    "subject": "Reminder",
                    "message": loader.render_to_string(
                        "academy/email_template.html", {"message": form.cleaned_data["message"]}, request
                    ),
                    "from_email": form.cleaned_data["from_email"],
                },
                eta=form.cleaned_data["datetime"],
            )
            return redirect(reverse("academy:index"))
    else:
        form = ReminderForm()
    return render(request, "academy/contact_us.html", {"form": form})

celery_beat/views.py
from django.shortcuts import render

# Create your views here.

academy/templates/academy/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
<style>

    ul:first-child {
        float: right;
        width: 100px;
        margin-right: 30px;
    }

#TopButton {
    display: none;
    position: fixed;
    bottom: 40px;
    right: 50px;
    z-index: 99;
    border: none;
    outline: none;
    background-color: lightgoldenrodyellow;
    color: black;
    cursor: pointer;
    padding: 15px;
    border-radius: 24px;
}

#TopButton:hover {
    background-color: darkseagreen;
}
</style>
    {% block Title %}
         <title>Index</title>
    {% endblock Title %}
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="stylesheet" href="{% static "css/fieldset.css" %}">
    {% block css_additional %}{% endblock css_additional %}
</head>
<body>

 <div class="row">
    <div class="col-sm-2">
    <ul>
        <li><a href="/admin/">Login</a></li>
    </ul>
        {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url "academy:index" %}"><b>Home</b></a></li>
                    <li><a href="{% url "academy:students_list" %}">All students</a></li>
                    <li><a href="{% url "academy:subject_list" %}">All subjects</a></li>
                    <li><a href="{% url "academy:teacher_list" %}">All teachers</a></li>
                </ul>
            <br>
                <ul>
                    <li><a href="{% url "academy:contact-us" %}">Contact Us</a></li>
                </ul>
        {% endblock sidebar %}
    </div>
 </div>
 <p>
{% block content %}
{% endblock content %}

{% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&larr; First page</a>
                    <br>
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">&laquo; Previous page</a>
                {% endif %}
              <span class="page-current">
                    <strong>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</strong>
                </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next page &raquo;</a>
                  <br>
                  <a href="?page={{ page_obj.paginator.num_pages }}">Last page &rarr;</a>
              {% endif %}
            </span>
          </div>
        {% endif %}
{% endblock %}

<button onclick="topFunction()" id="TopButton" title="Go to top">Back to Top</button>
<script>
// Get the button
let mybutton = document.getElementById("TopButton");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>

</body>
</html>

academy/templates/academy/contact_us.html
{% load static %}
<link rel="stylesheet" href="{% static "css/base.css" %}">
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form action="{% url "academy:contact-us" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
    <input type="reset" value="Reset">
</form>
<h3><a href="{% url "academy:index" %}">Home</a></h3>

</body>
</html>

academy/templates/academy/email_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h5>Hi, Sir</h5>
    <br>
    <p>{{ message }}</p>
    <br>
    <p>Best Regards...</p>
</body>
</html>

academy/templates/academy/index.html
{% extends "academy/base.html" %}
{% load static %}

{% block css_additional %}
    <link rel="stylesheet" href="{% static "css/base.css" %}">
{% endblock css_additional %}

{% block content %}
  <h1>Local Library Home</h1>

  <p><h2>Welcome to <strong>Test Academy</strong>, simplest Django website developmentally based on <a
      href="https://github.com/KhvPaul/django_example_project/tree/main">django_example_project</a> provided by <a
          href="https://github.com/KhvPaul">KhvPaul</a>.</h2></p>
  <p><h2>In this project an attempt was made to create a Django skeleton website and application, define URL mappings, views
    (including Generic List and Detail Views), models and templates.</h2></p>


  <center><h4>UML Models</h4></center>
  <p><center><h4>An UML diagram of the site's Django model structure is shown below. </h4></center></p>

  <div>
    <center><img src="{% static "images/academy.png" %}" alt="My image" style="height:640px; border: 4mm ridge rgba(211, 220, 50, .6);"/></center>
  </div>

{% endblock %}

academy/templates/academy/student_confirm_delete.html
{% extends "academy/base.html"  %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p><h3>Are you sure you want to delete "<em>{{ student }}</em>"?</h3></p>
        {{ form }}
        <input type="submit" value="Confirm">
    <input type="reset" value="Reset">
    </form>
{% endblock content %}

academy/templates/academy/student_detail.html
{% extends "academy/base.html" %}
{% load static %}

{% block content %}

  <h1>Student: {{ student.student_first_name}} {{ student.student_last_name}}</h1>
    <p><h3><a href="{% url "academy:student_updating" student.id %}">Update student</a></h3></p>
    <p><h3><a href="{% url "academy:student_delete" student.id %}">Delete student</a></h3></p>

{#  <p><strong>First name:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>#}
    <p><strong>First name:</strong> {{ student.student_first_name }}</p>
    <p><strong>Last name:</strong> {{ student.student_last_name }}</p>
    <p><strong>Course:</strong> {{ student.course }}</p>
    <p><strong>Teacher:</strong> {{ student.teacher.all|join:", " }}</p>
    <strong>Subjects:</strong> {% for subject in student.subjects_set.all%}
        <a href="{{ subject.get_absolute_url }}"> {{ subject }}</a>
{% endfor %}
    <p><h3><a href="{% url "academy:students_profile" student.id %}">Student Profile Page</a></h3></p>
{% endblock %}

academy/templates/academy/student_form.html
{% extends "academy/base.html" %}
{% load static %}

{% block content %}

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    <input type="reset" value="Reset">
    </form>

{% endblock content %}

academy/templates/academy/student_profile.html
{% extends "academy/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student Profile</title>
</head>
<body>
{% block content %}
    <fieldset>
        <legend><h2>Student # {{ studentprofile.some_student }} Profile</h2></legend>
        <p><strong>Hobby:</strong> {{ studentprofile.hobby }}</p>
        <p><strong>Religion:</strong> {{ studentprofile.religion }}</p>
        <p><strong>Age:</strong> {{ studentprofile.age }}</p>
        <p><strong>Birth date:</strong> {{ studentprofile.birth_date }}</p>
    </fieldset>
{% endblock content %}
</body>
</html>

academy/templates/academy/student_update_form.html
{% extends "academy/base.html" %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
        <input type="reset" value="Reset">
    </form>

{% endblock content %}

academy/templates/academy/students_list.html
{% extends "academy/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block Title %}
        <title>Students</title>
    {% endblock Title %}
</head>
<body>
{% block content %}
        <br>
<h3><a href="{% url "academy:student_creation" %}"> &#9998; <em>Create Student</em></a></h3>
    <br>
    <fieldset>
    <h1>List of the Students:</h1>
    </fieldset>
{% if student_list %}
    <h2>Average course: {{ avg_count }} </h2>
{#    <h2>Students count: {{ student_list }} </h2>#}
    <ul>
    {% for student in student_list %}
        <li>
            <a href="{% url "academy:student_detail" student.id %}"><strong>{{ student.student_first_name }}
                {{ student.student_last_name }}</strong></a>
            <p>
            <strong>Teachers:</strong> {{ student.teacher.all|join:", " }}
            <p>
            <strong>Subjects:</strong> {{ student.subjects_set.all|join:", " }}
            <p>
            <strong>Student Profile: </strong> {{ student.studentprofile.some_student }}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No student are available</p>
{% endif %}
{% endblock content %}

</body>
</html>

academy/templates/academy/subject_detail.html
{% extends "academy/base.html" %}

{% block content %}

  <h1>Subject: {{ subjects.subject_name}}</h1>
    <p><strong>Amount of lectures:</strong> {{ subjects.lecture_amount }} lectures</p>
    <p><strong>Lecture duration:</strong> {{ subjects.lecture_duration }} hour(s)</p>
    <p><strong>Teacher:</strong> {{ subjects.teacher_name}}</p>
{#    <p><strong>Student(s):</strong>{{ subjects.student_name.all }}</p>#}
    <p><strong>Student(s):</strong> {% for student in subjects.student_name.all %} <a href="{{ student.get_absolute_url }}">{{ student }}</a>
{% endfor %}
    <p><strong>Student count: </strong>{{ subjects.student_count }}</p>
{% endblock %}


{#{% for subject in student.subjects_set.all%}#}
{#        <a href="{% url "academy:subject_detail" student.id %}"> {{ subject }}</a></p>#}
{#        <a href="{{ subject.get_absolute_url }}"> {{ subject }}</a></p>#}
{#{% endfor %}#}

academy/templates/academy/subject_list.html
{% extends "academy/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block Title %}
        <title>Subjects</title>
    {% endblock Title %}
{#    <title>Subjects</title>#}
</head>
<body>
{% block content %}
    <fieldset>
    <h1>List of Subjects:</h1>
    </fieldset>
{% if subjects_list %}
    <ul>
    {% for subject in subjects_list %}
{#        <li><a href="{{ subjects.get_absolute_url }}">{{ subjects.subject_name}}</a></li>#}
        <li>
            <a href="{% url "academy:subject_detail" subject.id %}">{{ subject.subject_name}}</a> (Teacher: {{ subject.teacher_name }})
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No subjects are available</p>
{% endif %}
{% endblock content %}

</body>
</html>

academy/templates/academy/teacher_detail.html
{% extends "academy/base.html" %}

{% block content %}

  <h1>Teacher: {{ teacher.teacher_first_name}} {{ teacher.teacher_last_name}}</h1>
    <p><strong>Seniority:</strong> {{ teacher.seniority }} years</p>
{#    <p><strong>Subjects:</strong> <a href="{% url "academy:subject" subjects.student_name %}">{{ student.subjects.all|join:", "}}</a></p>#}
{% endblock %}

academy/templates/academy/teacher_list.html
{% extends "academy/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block Title %}
        <title>Teachers</title>
    {% endblock Title %}
</head>
<body>
{% block content %}
    <fieldset>
    <h1>List of the Teachers:</h1>
    </fieldset>
{% if teacher_list %}
    <ul>
    {% for teacher in teacher_list %}
        <li>
            <a href="{% url "academy:teacher_detail" teacher.id %}">{{ teacher.teacher_first_name }} {{ teacher.teacher_last_name }}</a> (Subjects: {{ teacher.subjects_set.all|join:", " }})
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No teachers are available</p>
{% endif %}
{% endblock content %}

</body>
</html>